export type ConsultingTool = {
  id: string;
  title: string;
  label: string;
  desc: string;
  icon: string;
  url: string;
  color: string;
  cardColor: string;
  fixed?: boolean;
  staffOnly?: boolean;
  access: "public" | "guest_approved" | "approved" | "office";
  guestVisible?: boolean;  // true = 미승인·게스트도 볼 수 있는 도구
  highlight?: boolean;
  isNew?: boolean;
  editable?: boolean;
  chromeRecommended?: boolean;
  defaultEnabled?: boolean;
  category?: "customer" | "coverage" | "financial" | "planning" | "claims" | "face";
  placement?: "consulting" | "office";
  hideFromMainGrid?: boolean;
};

export const CONSULTING_TOOL_CATEGORIES: {
  id: NonNullable<ConsultingTool["category"]>;
  title: string;
  desc: string;
  tone: string;
  countTone: string;
}[] = [
  { id: "face", title: "대면상담", desc: "고객과 직접 만나 활용하는 핵심 상담 도구 5종", tone: "border-sky-500 text-sky-600", countTone: "bg-sky-50 text-sky-700" },
  { id: "customer", title: "고객 상담", desc: "고객 안내와 상담 근거 확인에 필요한 도구", tone: "border-sky-500 text-sky-600", countTone: "bg-sky-50 text-sky-700" },
  { id: "coverage", title: "보장 분석", desc: "보장 통계, 인수 기준, 교차설계 비교에 필요한 도구", tone: "border-sky-500 text-sky-600", countTone: "bg-sky-50 text-sky-700" },
  { id: "financial", title: "재무설계 상담", desc: "재무 분석, 현금흐름, 포트폴리오 제안에 필요한 상담 도구", tone: "border-indigo-500 text-indigo-600", countTone: "bg-indigo-50 text-indigo-700" },
  { id: "planning", title: "조회 및 서류안내", desc: "보장 조회와 청구 서류 안내에 필요한 도구", tone: "border-indigo-500 text-indigo-600", countTone: "bg-indigo-50 text-indigo-700" },
  { id: "claims", title: "수술 및 후유장해", desc: "질병, 수술, 장해 기준 확인에 필요한 도구", tone: "border-rose-500 text-rose-600", countTone: "bg-rose-50 text-rose-700" },
];

export const CONSULTING_TOOL_GROUPS: {
  id: "consulting" | "lookup" | "work";
  title: string;
  desc: string;
  toolIds: string[];
}[] = [
  {
    id: "consulting",
    title: "상담",
    desc: "고객 상담, 보장분석, 제안서 작성에 쓰는 핵심 도구",
    toolIds: [
      "show_first_coverage_check",
      "show_proposal",
      "show_insu",
      "show_finance",
      "show_financial_portfolio",
      "show_card_consult",
    ],
  },
  {
    id: "lookup",
    title: "조회·자료",
    desc: "상담 중 바로 확인하는 통계, 코드, 약관, 계산 자료",
    toolIds: [
      "show_coverage_stats",
      "show_premium_compare",
      "show_underwriting",
      "show_health_kr",
      "show_cont",
      "show_hira",
      "show_knia",
      "show_car_accident",
      "show_disease",
      "show_surgery",
      "show_disability",
      "show_calc",
      "show_gongsi",
    ],
  },
  {
    id: "work",
    title: "업무",
    desc: "고객 안내와 반복 업무에 연결되는 도구",
    toolIds: [
      "show_insurance_survey",
      "show_exam",
      "show_dm",
    ],
  },
];

// fixed=true 항목은 항상 true, defaultEnabled=false면 false, 나머지는 true
export const DEFAULT_MENU_STATUS: Record<string, boolean> = {
  show_first_coverage_check: true,  // fixed
  show_cont: true,                  // fixed
  show_hira: true,                  // fixed
  show_health_kr: true,             // fixed
  show_insurance_survey: true,      // fixed
  show_card_consult: true,          // fixed
  show_knia: true,                  // fixed
  show_coverage_stats: true,
  show_car_accident: true,
  show_disease: true,               // fixed
  show_premium_compare: true,
  show_surgery: true,
  show_disability: true,
  show_underwriting: true,
  show_insu: true,
  show_calc: true,
  show_financial_portfolio: true,
  show_finance: true,
  show_gongsi: true,                // fixed
  show_proposal: true,              // fixed
  show_exam: true,
  show_dm: true,
}

export const CONSULTING_TOOLS: ConsultingTool[] = [
  {
    id: "show_exam",
    title: "자격시험",
    label: "자격시험",
    desc: "모의고사와 합격 전략, 최신 시험정보 확인",
    icon: "exam",
    url: "/exam-hub/index.html",
    color: "border-blue-500",
    cardColor: "border-blue-500 text-blue-700",
    fixed: true,
    access: "public",
    guestVisible: true,
    editable: false,
    hideFromMainGrid: true,
    category: "planning",
  },
  {
    id: "show_dm",
    title: "DM 발송",
    label: "DM 발송",
    desc: "고객 대상 메시지 쉽고 빠르게 발송",
    icon: "dm",
    url: "/dm",
    color: "border-violet-500",
    cardColor: "border-violet-500 text-violet-700",
    fixed: true,
    access: "guest_approved",
    editable: false,
    category: "customer",
  },
  {
    id: "show_first_coverage_check",
    title: "첫 상담 보장체크",
    label: "첫 상담 보장체크",
    desc: "고객 현재 보장으로 암·뇌·심장·수술·간병 준비율을 바로 확인",
    icon: "shield",
    url: "/first-coverage-check",
    color: "border-amber-500",
    cardColor: "border-amber-500 text-amber-700",
    fixed: true,
    staffOnly: true,
    access: "approved",
    highlight: true,
    isNew: true,
    editable: true,
    defaultEnabled: false,
    category: "face",
  },
  {
    id: "show_proposal",
    title: "제안서 생성",
    label: "제안서 생성",
    desc: "단독 또는 비교 제안서를 인포그래픽 형태로 3장 이내 가로형으로 제작",
    icon: "document",
    url: "/insurance-tools/proposal",
    color: "border-amber-500",
    cardColor: "border-amber-500 text-amber-700",
    fixed: true,
    staffOnly: true,
    access: "approved",
    highlight: true,
    isNew: true,
    editable: false,
    category: "face" as const,
  },
  {
    id: "show_cont",
    title: "숨은보험금",
    label: "숨은보험금",
    desc: "숨은보험금, 진료기록 확인",
    icon: "search",
    url: "https://cont.insure.or.kr/cont_web/intro.do",
    color: "border-emerald-500",
    cardColor: "border-emerald-500 text-emerald-600",
    fixed: true,
    access: "public",
    guestVisible: true,
    highlight: false,
    editable: false,
    chromeRecommended: true,
    category: "face",
  },
  {
    id: "show_hira",
    title: "진료기록 확인",
    label: "진료기록 확인",
    desc: "건강e음 어플 활용 제안",
    icon: "hospital",
    url: "https://www.hira.or.kr/dummy.do?pgmid=HIRAA030009200000",
    color: "border-orange-500",
    cardColor: "border-orange-500 text-orange-600",
    fixed: true,
    access: "public",
    guestVisible: true,
    highlight: false,
    editable: false,
    category: "face",
  },
  {
    id: "show_health_kr",
    title: "먹는약 확인",
    label: "먹는약 확인",
    desc: "고객의 복용약을 검색하여 확인합니다.(예시 항암약인지 아닌지)",
    icon: "pill",
    url: "https://health.kr/",
    color: "border-emerald-500",
    cardColor: "border-emerald-500 text-emerald-600",
    fixed: true,
    access: "public",
    guestVisible: true,
    highlight: false,
    editable: false,
    category: "planning",
  },
  {
    id: "show_insurance_survey",
    title: "내보험 바로 알기",
    label: "내보험 바로 알기",
    desc: "내보험바로 알기 캠페인",
    icon: "checklist",
    url: "/insurance-survey",
    color: "border-sky-500",
    cardColor: "border-sky-500 text-sky-600",
    fixed: true,
    access: "public",
    highlight: false,
    editable: false,
    category: "face",
  },
  {
    id: "show_card_consult",
    title: "고객상담 카드",
    label: "고객상담 카드",
    desc: "카드를 선택해 나에게 맞는 보험이 설계되었는지 필요한 것은 무엇인지 확인해보세요",
    icon: "checklist",
    url: "/card-consult",
    color: "border-sky-500",
    cardColor: "border-sky-500 text-sky-600",
    fixed: true,
    access: "public",
    highlight: false,
    editable: false,
    category: "face",
  },
  {
    id: "show_knia",
    title: "사고 과실비율",
    label: "사고 과실비율",
    desc: "자동차 사고 과실비율 검색",
    icon: "crash",
    url: "https://accident.knia.or.kr",
    color: "border-indigo-500",
    cardColor: "border-indigo-500 text-indigo-600",
    fixed: true,
    access: "public",
    guestVisible: true,
    editable: false,
    category: "planning",
  },
  {
    id: "show_coverage_stats",
    title: "보장 통계",
    label: "보장 통계",
    desc: "상담에 활용하는 통계 이미지와 멘트",
    icon: "chart",
    url: "/insurance-tools/coverage-stats",
    color: "border-sky-500",
    cardColor: "border-sky-500 text-sky-600",
    access: "guest_approved",
    editable: true,
    category: "coverage",
  },
  {
    id: "show_car_accident",
    title: "부상등급 계산",
    label: "부상등급 계산",
    desc: "진단 및 치료에 따른 자부상 등급확인 및 금액계산",
    icon: "calculator-car",
    url: "/insurance-tools/car-accident",
    color: "border-indigo-500",
    cardColor: "border-indigo-500 text-indigo-600",
    access: "guest_approved",
    guestVisible: true,
    editable: true,
    category: "planning",
  },
  {
    id: "show_disease",
    title: "질병코드 검색",
    label: "질병코드 검색",
    desc: "KCD 질병사인분류 검색",
    icon: "code",
    url: "https://kcdcode.kr/browse/main",
    color: "border-rose-500",
    cardColor: "border-rose-500 text-rose-600",
    fixed: true,
    access: "public",
    editable: false,
    category: "claims",
  },
  {
    id: "show_premium_compare",
    title: "보험료 비교",
    label: "보험료 비교",
    desc: "건강보험, 종신, 저축성 비교",
    icon: "compare",
    url: "/insurance-tools/premium-compare",
    color: "border-indigo-500",
    cardColor: "border-indigo-500 text-indigo-600",
    access: "guest_approved",
    editable: true,
    category: "coverage",
  },
  {
    id: "show_surgery",
    title: "수술비 조회",
    label: "수술비 조회",
    desc: "종별 수술비와 약관 조회",
    icon: "surgery",
    url: "/insurance-tools/surgery",
    color: "border-rose-500",
    cardColor: "border-rose-500 text-rose-600",
    access: "guest_approved",
    editable: true,
    category: "claims",
  },
  {
    id: "show_disability",
    title: "장해등급 조회",
    label: "장해등급 조회",
    desc: "상해와 질병 장해분류 가이드",
    icon: "document",
    url: "/insurance-tools/disability",
    color: "border-rose-500",
    cardColor: "border-rose-500 text-rose-600",
    access: "guest_approved",
    editable: true,
    category: "claims",
  },
  {
    id: "show_underwriting",
    title: "간편인수 확인",
    label: "간편인수 확인",
    desc: "보험사별 인수 기준 참고 자료",
    icon: "checklist",
    url: "/underwriting/index.html",
    color: "border-sky-500",
    cardColor: "border-sky-500 text-sky-600",
    access: "guest_approved",
    editable: true,
    category: "coverage",
  },
  {
    id: "show_insu",
    title: "보장분석 PRO",
    label: "보장분석 PRO",
    desc: "정밀 보장분석 시스템",
    icon: "shield",
    url: "/coverage-pro",
    color: "border-indigo-500",
    cardColor: "border-indigo-500 text-indigo-600",
    staffOnly: true,
    access: "approved",
    editable: true,
    category: "coverage",
  },
  {
    id: "show_calc",
    title: "금융계산기",
    label: "금융계산기",
    desc: "대출, 적금, 수익률 계산",
    icon: "calculator",
    url: "/financial-calc",
    color: "border-indigo-500",
    cardColor: "border-indigo-500 text-indigo-600",
    access: "guest_approved",
    editable: true,
    category: "financial",
  },
  {
    id: "show_financial_portfolio",
    title: "재무설계 포트폴리오",
    label: "재무설계 포트폴리오",
    desc: "고객별 재무정보, 현금흐름, 재무지수, 자산배분전략을 PDF로 출력",
    icon: "finance",
    url: "/financial-portfolio",
    color: "border-teal-500",
    cardColor: "border-teal-500 text-teal-600",
    access: "guest_approved",
    editable: true,
    category: "financial",
  },
  {
    id: "show_finance",
    title: "재무설계 PRO",
    label: "재무설계 PRO",
    desc: "종합 금융 플래너 리포트",
    icon: "finance",
    url: "/financial-planner/index.html",
    color: "border-indigo-500",
    cardColor: "border-indigo-500 text-indigo-600",
    staffOnly: true,
    access: "approved",
    editable: true,
    category: "financial",
  },
  {
    id: "show_gongsi",
    title: "상품공시 조회",
    label: "상품공시 조회",
    desc: "각 보험사 상품 약관 공시",
    icon: "document",
    url: "/gongsi.html",
    color: "border-slate-400",
    cardColor: "border-slate-400 text-slate-500",
    fixed: true,
    access: "public",
    highlight: false,
    editable: false,
    category: "planning" as const,
  },
]
