export type ConsultingTool = {
  id: string;
  title: string;
  label: string;
  desc: string;
  icon: string;
  url: string;
  color: string;
  cardColor: string;
  fixed?: boolean;
  staffOnly?: boolean;
  access: "public" | "approved";
  highlight?: boolean;
  editable?: boolean;
  chromeRecommended?: boolean;
  category?: "customer" | "coverage" | "financial" | "planning" | "claims";
  placement?: "consulting" | "office";
};

export const CONSULTING_TOOL_CATEGORIES: {
  id: NonNullable<ConsultingTool["category"]>;
  title: string;
  desc: string;
  tone: string;
  countTone: string;
}[] = [
  { id: "customer", title: "고객 상담", desc: "고객 안내와 상담 근거 확인에 필요한 도구", tone: "border-sky-500 text-sky-600", countTone: "bg-sky-50 text-sky-700" },
  { id: "coverage", title: "보장 분석", desc: "보장 통계, 인수 기준, 교차설계 비교에 필요한 도구", tone: "border-sky-500 text-sky-600", countTone: "bg-sky-50 text-sky-700" },
  { id: "financial", title: "재무설계 상담", desc: "재무 분석과 금융 계산에 필요한 상담 도구", tone: "border-indigo-500 text-indigo-600", countTone: "bg-indigo-50 text-indigo-700" },
  { id: "planning", title: "설계 및 보장분석", desc: "보장 점검과 사고 상담에 필요한 도구", tone: "border-indigo-500 text-indigo-600", countTone: "bg-indigo-50 text-indigo-700" },
  { id: "claims", title: "수술 및 후유장해", desc: "질병, 수술, 장해 기준 확인에 필요한 도구", tone: "border-rose-500 text-rose-600", countTone: "bg-rose-50 text-rose-700" },
];

export const CONSULTING_TOOLS: ConsultingTool[] = [
  {
    id: "show_cafe",
    title: "보험정보 카페",
    label: "보험정보 카페",
    desc: "네이버 카페 바로가기",
    icon: "cafe",
    url: "https://cafe.naver.com/signal1035",
    color: "border-emerald-500",
    cardColor: "border-emerald-500 text-emerald-600",
    fixed: true,
    access: "public",
    highlight: true,
    editable: false,
  },
  {
    id: "show_cont",
    title: "숨은보험금",
    label: "숨은보험금",
    desc: "숨은보험금, 진료기록 확인",
    icon: "search",
    url: "https://cont.insure.or.kr/cont_web/intro.do",
    color: "border-emerald-500",
    cardColor: "border-emerald-500 text-emerald-600",
    fixed: true,
    access: "public",
    highlight: true,
    editable: false,
    chromeRecommended: true,
  },
  {
    id: "show_hira",
    title: "진료기록 확인",
    label: "진료기록 확인",
    desc: "건강e음 어플 활용 제안",
    icon: "hospital",
    url: "https://www.hira.or.kr/dummy.do?pgmid=HIRAA030009200000",
    color: "border-orange-500",
    cardColor: "border-orange-500 text-orange-600",
    fixed: true,
    access: "public",
    highlight: true,
    editable: false,
  },
  {
    id: "show_health_kr",
    title: "약학정보원",
    label: "약학정보원",
    desc: "고객의 복용약을 검색하여 확인합니다.(예시 항암약인지 아닌지)",
    icon: "pill",
    url: "https://health.kr/",
    color: "border-emerald-500",
    cardColor: "border-emerald-500 text-emerald-600",
    fixed: true,
    access: "public",
    highlight: true,
    editable: false,
  },
  {
    id: "show_insurance_survey",
    title: "내보험 바로 알기",
    label: "내보험 바로 알기",
    desc: "내보험바로 알기 캠페인",
    icon: "checklist",
    url: "/insurance-survey",
    color: "border-sky-500",
    cardColor: "border-sky-500 text-sky-600",
    fixed: true,
    access: "public",
    highlight: true,
    editable: false,
  },
  {
    id: "show_knia",
    title: "교통사고 과실비율 조회",
    label: "교통사고 과실비율 조회",
    desc: "자동차 사고 과실비율 검색",
    icon: "crash",
    url: "https://accident.knia.or.kr",
    color: "border-indigo-500",
    cardColor: "border-indigo-500 text-indigo-600",
    fixed: true,
    access: "public",
    editable: false,
    category: "planning",
  },
  {
    id: "show_coverage_stats",
    title: "보장별 통계 자료",
    label: "보장별 통계 자료",
    desc: "상담에 활용하는 통계 이미지와 멘트",
    icon: "chart",
    url: "/insurance-tools/coverage-stats",
    color: "border-sky-500",
    cardColor: "border-sky-500 text-sky-600",
    staffOnly: true,
    access: "approved",
    editable: true,
    category: "coverage",
  },
  {
    id: "show_car_accident",
    title: "자동차 사고부상등급표 계산",
    label: "자동차 사고부상등급표 계산",
    desc: "진단 및 치료에 따른 자부상 등급확인 및 금액계산",
    icon: "calculator-car",
    url: "/insurance-tools/car-accident",
    color: "border-indigo-500",
    cardColor: "border-indigo-500 text-indigo-600",
    staffOnly: true,
    access: "approved",
    editable: true,
    category: "planning",
  },
  {
    id: "show_disease",
    title: "질병코드 조회",
    label: "질병코드 조회",
    desc: "KCD 질병사인분류 검색",
    icon: "code",
    url: "https://kcdcode.kr/browse/main",
    color: "border-rose-500",
    cardColor: "border-rose-500 text-rose-600",
    fixed: true,
    access: "public",
    editable: false,
    category: "claims",
  },
  {
    id: "show_premium_compare",
    title: "보험료 비교",
    label: "보험료 비교",
    desc: "건강보험, 종신, 저축성 비교",
    icon: "compare",
    url: "/insurance-tools/premium-compare",
    color: "border-indigo-500",
    cardColor: "border-indigo-500 text-indigo-600",
    staffOnly: true,
    access: "approved",
    editable: true,
    category: "coverage",
  },
  {
    id: "show_surgery",
    title: "수술비 검색",
    label: "수술비 검색",
    desc: "종별 수술비와 약관 조회",
    icon: "surgery",
    url: "/insurance-tools/surgery",
    color: "border-rose-500",
    cardColor: "border-rose-500 text-rose-600",
    staffOnly: true,
    access: "approved",
    editable: true,
    category: "claims",
  },
  {
    id: "show_disability",
    title: "장해분류표",
    label: "장해분류표",
    desc: "상해와 질병 장해분류 가이드",
    icon: "document",
    url: "/insurance-tools/disability",
    color: "border-rose-500",
    cardColor: "border-rose-500 text-rose-600",
    staffOnly: true,
    access: "approved",
    editable: true,
    category: "claims",
  },
  {
    id: "show_underwriting",
    title: "회사별 간편 인수 확인",
    label: "회사별 간편 인수 확인",
    desc: "보험사별 인수 기준 참고 자료",
    icon: "checklist",
    url: "/underwriting/index.html",
    color: "border-sky-500",
    cardColor: "border-sky-500 text-sky-600",
    staffOnly: true,
    access: "approved",
    editable: true,
    category: "coverage",
  },
  {
    id: "show_insu",
    title: "보장분석 PRO",
    label: "보장분석 PRO",
    desc: "정밀 보장분석 시스템",
    icon: "shield",
    url: "/insu.html",
    color: "border-indigo-500",
    cardColor: "border-indigo-500 text-indigo-600",
    staffOnly: true,
    access: "approved",
    editable: true,
    category: "planning",
  },
  {
    id: "show_calc",
    title: "금융계산기",
    label: "금융계산기",
    desc: "대출, 적금, 수익률 계산",
    icon: "calculator",
    url: "/financial-calc",
    color: "border-indigo-500",
    cardColor: "border-indigo-500 text-indigo-600",
    staffOnly: true,
    access: "approved",
    editable: true,
    category: "financial",
  },
  {
    id: "show_finance",
    title: "재무 분석 도구",
    label: "재무 분석 도구",
    desc: "종합 금융 플래너 리포트",
    icon: "finance",
    url: "/financial-planner/index.html",
    color: "border-indigo-500",
    cardColor: "border-indigo-500 text-indigo-600",
    staffOnly: true,
    access: "approved",
    editable: true,
    category: "financial",
  },
  {
    id: "show_gongsi",
    title: "보험상품 공시",
    label: "보험상품 공시",
    desc: "각 보험사 상품 약관 공시",
    icon: "document",
    url: "/gongsi.html",
    color: "border-slate-400",
    cardColor: "border-slate-400 text-slate-500",
    fixed: true,
    access: "approved",
    editable: false,
    placement: "office",
  },
];

export const DEFAULT_MENU_STATUS = CONSULTING_TOOLS.reduce<Record<string, boolean>>((acc, tool) => {
  acc[tool.id] = true;
  return acc;
}, {});
